network/urls.py
from django.urls import path

from . import views

app_name = 'network'

urlpatterns = [
    path("", views.index, name="index"),
    path('all_post/<int:page>', views.all_post, name='all_post'),
    path("create_post", views.create_post, name='create_post'),
    path('edit_post/<int:post_id>', views.edit_post, name='edit_post'),
    path('follow_switch/<int:user_id>', views.follow_switch, name='follow_switch'),
    path("profile_page/<int:user_id>", views.profile_page, name="profile_page"),
    path('user_posts', views.user_posts,name='user_posts'),
    path('liking/<int:post_id>',views.liking,name='liking'),
    path('post_comment/<int:post_id>', views.post_comment, name='post_comment'),
    path('view_comment/<int:post_id>', views.view_comment, name='view_comment'),
    path("following_post/<int:page>", views.following_post, name="following_post"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

project4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import datetime

# this file contains all the model used within the application 
# each class represent a table and its attribute

# this this the User model for storing personal information relating to a particular User,
# using django AbstractUser class we imported the field and dont need to create a new one.
class User(AbstractUser):

    #  created a serialize function for easy use or convertion to JSON 
    def serialize(self):
        return {
            'id': self.id,
            'username': self.username,
            'email': self.email,
            'date_joined': self.date_joined.strftime("%b %d %Y"),
            'last_login' : self.last_login.strftime("%b %d %Y"),
        }

# this class model represent  and stores a Post created by each User. 
# each post is connected to a user who created the post 
class Post(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="posts")
    post_content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    

    # this is function returns a string representation of the information about the Post data
    def __str__(self):
        return f'{self.post_content} by {self.user} at {self.pub_date}'

     #  created a serialize function for easy use or convertion to JSON
    def serialize(self):
        return {
            'id' : self.id,
            'user_id':self.user.id,
            'user': self.user.username,
            'post_content': self.post_content,
            'pub_date' : self.pub_date,
            'no_likes': self.liked_post.count(),
            'no_comment' : self.post_comment.count(),
        }

# Like class store data related to the each user and a post if the user choose to like it or not,
# .
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name="user_likes")
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="liked_post")
    likes = models.BooleanField(default=False)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.post.post_content} -> {self.likes} likes'

    #  created a serialize function for easy use or convertion to JSON
    def serialize(self):
        return {
        'user_id': self.user.id,
        'post_id': self.post.id,
        'likes': self.likes,
        'pub_date':self.pub_date,
    }

# using the django ManyToMany db connector Following class store each user being followed by another
# user and each user following other user and makes retrieving and representing this information possible.
class Following(models.Model):
    user = models.ManyToManyField(User, related_name="follower")
    followings = models.ManyToManyField(User, related_name="followings")
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.all()}, {self.followings.all()}'

    #  created a serialize function for easy use or convertion to JSON
    def serialize(self):
        return {
            'user': [user.username for user in self.user.all()],
            'user_id': [user.id for user in self.user.all()],
            'following':[following.username for following in self.followings.all()],
            'following_id': [following.id for following in self.followings.all()],
        }


class UserFollowing(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    following = models.ForeignKey(Following, on_delete=models.CASCADE)


# Comment class store data related to the each user and a post 
# if the user choose to comment on it or not,
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "user_comment")
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name="post_comment")
    comment = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    #  created a serialize function for easy use or convertion to JSON
    def serialize(self):
        return {
             'user':self.user.username,
            'user_id':self.user.id,
            'post_id': self.post.id,
            'comment':self.comment,
            'pub_date': self.pub_date,
        }

network/views.py
import json
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect,JsonResponse
from django.shortcuts import render,redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings

from operator import itemgetter, attrgetter
from .models import Like, User,Post,Following,Comment
from .helper import addPaginator, is_liked, is_original_user
'''
most function returns the a json object after verifying and validating input.
thus this application works mostly as an Api 
using Javascript to display and format how information is handled within the front-end

'''
'''
@login_required annotation is used to make sure the user accessing the information is verified and signed in 
if not the user is directed to the login page
'''



# retrieve all the post from all the user
def index(request):

    total_post = Post.objects.all()

    # retrieve the post and order it by the newest one
    total_post = total_post.order_by("-pub_date").all()
    return render(request, "network/index.html",{
        'all_post': total_post
    })



def all_post(request, page):
    # retrieve all the post 
    total_post = Post.objects.all()

    # and order it by the newest ones first
    init_post = total_post.order_by("-pub_date").all()

    # create a new paginator using the addpaginator helper function
    paginated = addPaginator(init_post, page)

    # create a empty list objects to append each post after changes has been made through iteration
    total = []

    # loops through the new list of post object return by addpaginator 
    # and add extra information.
    for posts in paginated['total']:

        # for each post convert it to a object which can easily be converted to Json 
        # i.e ( dict object in python)
        pos = posts.serialize()

        # if the post was created by the current user then original user is True else False
        is_original_user(posts, request, pos)
        
        # check if the current user liked this post if liked return True else False
        is_liked(posts, request, pos)

        # append the current post to the created list called total after converting to json-type 
        # object and added extra information
        total.append(pos)
    
    # change the content of  paginated['total'] with the new improved content
    paginated['total'] = total
       
    # return the information as a JSON objects and safe=false because total contain a pythin dict
    return JsonResponse(paginated, safe=False)


# csrf_exempt used to by-pass CSRF checks but should not b used during production.
@csrf_exempt
@login_required(login_url='network:login')
def following_post(request, page):
    '''
    this function retrieves only post made user which the current user is following and return as a Json formats
    '''

    # create an empty list object
    post_follow =[]

    # return a list of following objects 
    follow =  Following.objects.filter(user=request.user)

    # loops through the list of following objects (follow) and for each objects get the user 
    # the current user is following 
    for u in follow:
       init_post = Post.objects.filter(user=u.followings.first())
       post_follow.extend(init_post) 

    # sort through and place the current at the top
    post_follow.sort(key=attrgetter('pub_date'), reverse=True)

    # create a new paginator using the addpaginator helper function
    paginated = addPaginator(post_follow, page)

    # create an empty list to add the list of post object including
    # extra information for each post object
    total = []

    # loop through the list of post object return from addpaginator
    for posts in paginated['total']:
        # for each post convert it to a object which can easily be converted to Json
        # i.e ( dict object in python)
        pos = posts.serialize()

        # if the post was created by the current user then original user is True else False
        is_original_user(posts, request, pos)

        # check if the current user liked this post if liked return True else False
        is_liked(posts, request, pos)

        # append the current post to the created list called total after converting to json-type
        # object and added extra information
        total.append(pos)

    # change the content of  paginated['total'] with the new improved content
    paginated['total'] = total

    # return the information as a JSON objects and safe=false because total contain a pythin dict
    return JsonResponse(paginated, safe=False)

# csrf_exempt used to by-pass CSRF checks but should not b used during production.
@csrf_exempt
@login_required(login_url='network:login')
def edit_post(request, post_id):

    '''
    This function allows the user to edit a post which was already created by first checking if the 
    request was a GET or PUT, if the request was GET it return post to be edited to the user.
    if the request user do not match the original user the request is denied to save an edited 
    post the request method has to a PUT and validation are made to determine if the edit should
    be save
    '''

    # checks if the request method is a GET
    if request.method =='GET':

        # if its a GET, try to  access that post if an error is created
        # return an error back to the user.
        try:
            posts = Post.objects.get(pk=post_id)
        except Post.DoesNotExist:
            return JsonResponse({'error':'no permission to edit post'}, status=404)
        
        # if the current user do not match the user who created the post return an error
        # else return the post back to the user.
        if not posts.user == request.user:
            return JsonResponse({'error':'NOT ALLOWED'}, status=401)
        else:
            return JsonResponse(posts.serialize(),safe=False)

    # checks if the request method is a PUT
    elif request.method == 'PUT':

        # try to  access that post if an error is created
        # return an error back to the user.
        try:
            posts = Post.objects.get(pk=post_id)
        except Post.DoesNotExist:
            return JsonResponse({'error':'no permission to edit post'}, status=404)
        
        # if the current user do not match the user who created the post return an error
        # else apply the changes made.
        if not posts.user == request.user:
            return JsonResponse({'error':'NOT ALLOWED'}, status=401)
        else:

            # retrieve the data from the returned json 
            data = json.loads(request.body)

            # get the post content called body
            body = data.get("body", "")

            # change the content of the post with the edited content and save it.
            posts.post_content = body
            posts.save()

            # if successful let the user know
            return JsonResponse({"message": 'Posted Successfully'}, status=201)
           

# csrf_exempt used to by-pass CSRF checks but should not b used during production.
@csrf_exempt
@login_required(login_url='network:login')
def liking(request,post_id):

    '''
    liking checks and updates post if the user choose to like it and unlike it 
    if the user is trying to unlike a post the returned json should be false else true for liking a post
    '''

    # checks if the request methods is a PUT
    if request.method =='PUT':
        # try to access the post using the post_id provided in the parameter
        try:
            liking_post = Post.objects.get(pk=post_id)
        
        # return an error if posts does not exist
        except Post.DoesNotExist:
            return JsonResponse({'error':'post does not exit or has been deleted'}, status=404)
        
        # access the json file provided and get the body containing the information 
        # needed to determine if the post was like or unliked
        liked = json.loads(request.body)

        # try to access and check if the post was already liked before 
        try:
            already_liked = Like.objects.get(
                user=request.user, post=liking_post
            )

        # if like dont exist meaning the post was never liked by this user
        except Like.DoesNotExist:
            # create a new like if none existed
            already_liked = Like.objects.create(
                user=request.user, post=liking_post
            )

        # if the user is trying to unlike a post 
        if liked.get('liked') == False:
            # delete the already like or created like for the post
            already_liked.delete()

            # and return the new number of likes for that post
            no_like = Like.objects.filter(post=liking_post).count()
            return JsonResponse({'message': 'Unliked','no_likes':no_like}, safe= False)

        # else is the user was trying to like a post
        elif liked.get('liked') == True:

            # change the Like.likes attritube from False to True and save it
            already_liked.likes = True
            already_liked.save()

            # return the current number likes for that post
            no_like = Like.objects.filter(post=liking_post).count()
            return JsonResponse({'message': 'Liked', 'no_likes': no_like}, safe=False)
    else:
        # request must be a PUT method before changes can be made
        return JsonResponse({"error": "PUT request required."}, status=400)

def view_comment(request, post_id):

    '''
    view_comment provides access to the comments for a particular post,
    make the post exist and returns the comments using a json format
    '''
    # trys to make connection withn the db and get access to the post and its comments
    try:
        posts = Post.objects.get(pk=post_id)

network/templates/network/index.html
{% extends "network/layout.html" %}
{%load static%}

{% block body %}
<div id="error-form">

</div>

<div id='post_content' class="">
    {% for f in all_post%}
    <div class="main-con container border col-10 bg-info col-md-7 mt-4">
        <h5 class="">
            <a id="{{f.user.id}}" class="text-decoration-none text-dark profile_id" href="#">
                {{f.user |capfirst}}</a>
        </h5>
        <div>
            <div class="d-flex justify-content-center bg-white">
                <h1>
                    <blockquote class="m-2 p-2">{{f.post_content | capfirst}}</blockquote>
                </h1>
            </div>
            <div id="">
                <span id="change_heart">
                    {% if f.user. %}{%endif%}
                    <a href="#" id="{{f.id}}" data-liked_type="liked"
                        class='text-decoration-none liked liked_heart text-white lead'>
                        &hearts;
                    </a>
                </span>
                <h6> <span class="no_like" data-post_id="{{f.id}}" class="like">{{f.liked_post.count}} </span>likes</h6>
            </div>
            <p> <span class="no_comment" data-post_id="{{f.id}}"></span>comment</p>

        </div>
    </div>

    {%empty%}
    nothing
    {%endfor%}
</div>

{% if user.is_authenticated %}

<div id='add_post' class="main-con container border col-10 bg-info col-md-7 mt-4">
    <form id="add-post-form">
        <div class="form-group lead">
            Post Content
        </div>
        <textarea class="form-control" id="post-body" placeholder="Body"></textarea>
        <div>
            <input type="submit" class="btn btn-primary" />
        </div>
    </form>
</div>

<div id='edit_post' class="main-con container border col-10 bg-info col-md-7 mt-4">
    <form id="edit-post-form">
        <div class="form-group lead">
            Post Content (edit)
        </div>
        <div id="edit-post-id"></div>
        <textarea class="form-control" id="edit-post-body" placeholder="Body"></textarea>
        <div>
            <input type="submit" class="btn btn-primary" />
        </div>
    </form>
</div>

<div id="profile_page" class="main-con  view-profile">
    <h5 class="text-white text-center m-5"> {{user.username | capfirst}} </h5>
    <div class="wrapper text-center">
        <div class="left ">
            <p><span class="text-danger">{{user.followings.count}}</span> followers</p>
            <ul class="list-unstyled">
                {%for f in user.followings.all%}
                {%for u in f.user.all%}
                <li><a id="{{u.id}}" class="text-decoration-none text-white profile_id" href="#">
                        {{ u | capfirst}}</a></li>
                {% endfor %}

                {% empty %}
                no follow yet.
                {% endfor %}
            </ul>
        </div>
        <div class="left ">
            <p><span class="text-danger">{{user.follower.count}}</span> following</p>
            <ul class="list-unstyled">
                {%for f in user.follower.all%}
                {%for u in f.followings.all%}
                <li><a id="{{u.id}}" class="text-decoration-none text-white profile_id" href="#">
                        {{ u | capfirst}}</a></li>
                {% endfor %}

                {% endfor %}
            </ul>
        </div>
        <div class="right">
            <div class="info">
                <h3>Information</h3>

                <div class="info_data">

                    <div class="data">
                        <h4>Email</h4>
                        <p>{{user.email}}</p>
                    </div>

                    <div class="data">
                        <h4>created on</h4>
                        <p>{{user.date_joined}}</p>
                    </div>
                </div>
            </div>

            <div class="info">
                <h3>Other information</h3>

                <div class="info_data">

                    <div class="data">
                        <h4>Total Post</h4>
                        <p><strong>{{user.posts.count}}</strong></p>
                    </div>

                    <div class="data">
                        <h4>Last posted on</h4>
                        <p>{{user.posts.last.pub_date}}</p>
                    </div>
                </div>
            </div>
        </div>

    </div>
<div class="container">
    <div id="og-user-posts" class="row mt-5">
        

    </div>
      
</div>
</div>


<div id='following-post-content' class="">

</div>

<div id="view_profile" class="">
    <div class="container">
        <div class="row mt-5 ">
            <h5 class="text-white lead text-center  col-2" id="profile_username"> </h5>
            <button id="" class=" link button-link text-danger follow_id"></button>

        </div>
    </div>
    <div class="container">
    <div class="wrapper">
        <div class="left ">
            <p><span id="no_follower" class="text-danger"></span> followers</p>
            <ul id="profile_follower" class="list-unstyled">
            </ul>
        </div>
        <div class="left ">
            <p><span id="no_following" class="text-danger"></span> following</p>
            <ul class="list-unstyled" id="profile_following">
            </ul>
        </div>
        <div class="right">
            <div class="info">
                <h3>Information</h3>

                <div class="info_data">

                    <div class="data">
                        <h4>Email</h4>
                        <p id="profile_email"></p>
                    </div>

                    <div class="data">
                        <h4>Joined on</h4>
                        <p id="profile_joined"></p>
                    </div>
                </div>
            </div>

            <div class="info">
                <h3>Other information</h3>

                <div class="info_data">

                    <div class="data">
                        <h4>Total post</h4>
                        <p id="total_post"></p>
                    </div>

                    <div class="data">
                        <h4 id="">Last seen</h4>
                        <p><strong id="last_seen"></strong></p>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<div class="container">
    <div id="user-posts" class="row mt-5">
        

    </div>
      
</div>

</div>

{% endif %}
{% endblock %}


{% block script %}
<script src="{% static 'network/network.js' %}"></script>
{% endblock %}

network/templates/network/layout.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Social Network{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'network/styles.css' %}" rel="stylesheet">
    
    {% block script %}
    {% endblock %}
</head>

<body class="bg-dark">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Network</a>

        <div>
            <ul class="nav mr-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <button class="nav-link button-link text-info" id="my_profile"><strong>
                            {{ user.username | title}}
                        </strong></button>
                </li>

                <li class="nav-item">
                    <button class="nav-link button-link" id="view_post">All Post</button>
                </li>

                <li class="nav-item">
                    <button class="nav-link button-link" id="addpost">Add Post</button>
                </li>
                <li class="nav-item">
                    <button class="nav-link button-link" id="following">Following</button>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="body container ">
        {% block body %}
        {% endblock %}
    </div>



</body>

</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

<div class=" d-flex justify-content-center">
    <form action="{% url 'network:login' %}" method="post" class="col-12 col-md-6 ">
        {% csrf_token %}
        <div class="form-group">
            <input type="hidden" name="{{ request.GET.next }}" value="{{ next }}" />
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
</div>
<p class="text-center"> Don't have an account? <a href="{% url 'network:register' %}">Register here.</a></p>

{% endblock %}

network/templates/network/post.html
{% extends "network/layout.html" %}
{%load static%}

{% block body %}
    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

<div>

{% for f in all_post%}
<div class="main-con container border col-10 bg-info col-md-7 mt-4">
    <h5 class=""><a class="text-decoration-none text-dark" href="{%url 'network:profile_page' f.user.id%}">
            1 {{f.user |capfirst}}</a></h5>
    <div>
        <div class="d-flex justify-content-center bg-white">
            <h1>
                <blockquote class="m-2 p-2">{{f.post_content | capfirst}}</blockquote>
            </h1>
        </div>
        <div>
            <span id="" class='text-danger likes'> &hearts; </span>
            <h6>likes</h6>
            <p>comment</p>
        </div>
    </div>
</div>
{%empty%}
nothing
{%endfor%}
</div>

















    {%for f in user.followings.all%}
    follower(followings)
    {%for u in f.user.all%}
    follower(user) {{ u }}
    {% endfor %}
    {%for u in f.followings.all%}
    followings {{ u }}
    {% endfor %}

    {% empty %}
    nothing
    {% endfor %}
    <br />
    {%for f in user.follower.all%}
    following(follower(user))
    {%for u in f.user.all%}
    follower(user) {{ u }}
    {% endfor %}
    {%for u in f.followings.all%}
    followings {{ u }}
    {% endfor %}

    {% endfor %}
    {{ user.follower.count }}
</div>
{% endblock %}

{% block script %}
<script src="{% static 'network/network.js' %}"></script>
{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
<div class="d-flex justify-content-center">
    <form action="{% url 'network:register' %}" method="post" class="col-12 col-md-6 ">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
</div>
   <p class="text-center"> Already have an account? <a href="{% url 'network:login' %}">Log In here.</a></p>

{% endblock %}